gui:
  theme:
    activeBorderColor:
      - '#fabd2f'
      - bold
    inactiveBorderColor:
      - '#928374'
    optionsTextColor:
      - '#83a598'
    selectedLineBgColor:
      - '#3c3836'
    selectedRangeBgColor:
      - '#3c3836'
    cherryPickedCommitBgColor:
      - '#689d6a'
    cherryPickedCommitFgColor:
      - '#282828'
    unstagedChangesColor:
      - '#fb4934'
    defaultFgColor:
      - '#ebdbb2'
