format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$fill\
$php\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$kubernetes\
$aws\
$docker_context\
$memory_usage\
$jobs\
$cmd_duration\
$time\
$line_break\
$character"""

add_newline     = false
palette         = 'gruvbox'
command_timeout = 500
scan_timeout    = 10

[directory]
style             = 'bold fg:blue bg:cursorline'
format            = '[$path ]($style)'
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo  = false
read_only         = ' 󰌾'
read_only_style   = 'fg:red bg:cursorline'

[directory.substitutions]
'Documents' = '󰈙 '
'Downloads' = ' '
'Music'     = ' '
'Pictures'  = ' '

[git_branch]
style  = 'fg:green bg:cursorline'
symbol = ' '
format = '[on](white bg:cursorline)[$symbol$branch ]($style)'

[git_commit]
commit_hash_length = 7
style              = 'fg:purple bg:cursorline'
format             = '[(\($hash$tag\) )]($style)'
only_detached      = true
tag_disabled       = false
tag_symbol         = ' 🏷 '

[git_state]
style        = 'fg:yellow bg:cursorline'
format       = '[\($state( $progress_current of $progress_total)\) ]($style)'
rebase       = 'REBASING'
merge        = 'MERGING'
revert       = 'REVERTING'
cherry_pick  = 'CHERRY-PICKING'
bisect       = 'BISECTING'
am           = 'AM'
am_or_rebase = 'AM/REBASE'

[git_status]
style      = 'fg:green bg:cursorline'
format     = '([$all_status$ahead_behind ]($style))'
conflicted = '🏳'
ahead      = '⇡${count}'
behind     = '⇣${count}'
diverged   = '⇕⇡${ahead_count}⇣${behind_count}'
untracked  = '?${count}'
stashed    = '📦'
modified   = '!${count}'
staged     = '+${count}'
renamed    = '»${count}'
deleted    = '✘${count}'

[fill]
symbol = '█'
style = 'fg:cursorline'

[php]
style    = 'blue bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[python]
style              = 'teal bg:cursorline'
symbol             = ' '
format             = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix       = ''
disabled           = false

[lua]
style    = 'blue bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[nodejs]
style    = 'blue bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[golang]
style    = 'blue bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[haskell]
style    = 'blue bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[rust]
style    = 'orange bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[ruby]
style    = 'blue bg:cursorline'
symbol   = ' '
format   = '[$symbol($version )]($style)'
disabled = false

[package]
style  = 'bg:cursorline'
symbol = '󰏗 '
format = '[$symbol$version ]($style)'

[aws]
symbol = ' '
style  = 'yellow bg:cursorline'
format = '[$symbol($profile )(\[$duration\] )]($style)'

[docker_context]
symbol            = ' '
style             = 'fg:teal bg:cursorline'
format            = '[$symbol$context ]($style)'
only_with_files   = true
detect_files      = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = []

[jobs]
symbol           = ' '
style            = 'red bg:cursorline'
number_threshold = 1
format           = '[$symbol]($style)'

[cmd_duration]
min_time          = 5
show_milliseconds = true
style             = 'fg:teal bg:cursorline'
format            = '[$duration ]($style)'

[git_metrics]
added_style   = 'fg:green bg:cursorline'
deleted_style = 'fg:red bg:cursorline'
format        = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled      = false

[kubernetes]
symbol       = '☸ '
style        = 'fg:blue bg:cursorline'
format       = '[$symbol$context( \($namespace\)) ]($style)'
disabled     = false
detect_files = ['k8s', 'Dockerfile', 'docker-compose.yml']

[memory_usage]
symbol    = '󰍛 '
style     = 'fg:yellow bg:cursorline'
format    = '[$symbol$ram ]($style)'
threshold = 75
disabled  = false

[time]
style       = 'fg:gray bg:cursorline'
format      = '[$time ]($style)'
time_format = '%T'
disabled    = true

[battery]
full_symbol        = '󰁹 '
charging_symbol    = '󰂄 '
discharging_symbol = '󰂃 '
unknown_symbol     = '󰁽 '
empty_symbol       = '󰂎 '
format             = '[$symbol$percentage ]($style)'

[[battery.display]]
threshold = 10
style     = 'bold red bg:cursorline'

[[battery.display]]
threshold = 30
style     = 'bold yellow bg:cursorline'

[[battery.display]]
threshold = 100
style     = 'bold green bg:cursorline'

[character]
success_symbol            = '[>](bold green bg:cursorline)'
error_symbol              = '[✗](bold red bg:cursorline)'
vimcmd_symbol             = '[<](bold green bg:cursorline)'
vimcmd_visual_symbol      = '[<](bold yellow bg:cursorline)'
vimcmd_replace_symbol     = '[<](bold purple bg:cursorline)'
vimcmd_replace_one_symbol = '[<](bold purple bg:cursorline)'

[palettes.gruvbox]
cursorline = '#3c3836'
dark_blue  = '#458588'
blue       = '#458588'
teal       = '#689d6a'
red        = '#fb4934'
orange     = '#d65d0e'
green      = '#98971a'
yellow     = '#d79921'
purple     = '#b16286'
gray       = '#a89984'
black      = '#282828'
white      = '#fbf1c7'
